### ISSUE TITLE
OpenXray Crashes to Desktop With Fresh Install and Stable OpenXray Release on Windows 10

### ISSUE THREAD

**Issue by Gold-Vibes** [OpenXRay/xray-16#1613]
**Describe the bug**
The game crashes when loading a new game at 1920x1080 for Enhanced Dx11 and Enhanced Dx10 video settings. I have many other games that run fine including Anomaly which is set to use DirectX11. I have tried this whole process twice starting from a fresh install both times. True Stalker on the OpenXray engine runs amazing and is an amazing game. 

**To Reproduce**
1. Fresh install of Call of Pripyat from GOG on Windows 10 Pro under C:\Games
2. Download the latest stable version and extract the archive for December 2021 RC1 from the link under https://github.com/OpenXRay/xray-16/wiki/[EN]-How-to-install-and-play (Which was followed from https://github.com/OpenXRay/xray-16 section "Install and Play")
3. Copy all files to the game root directory as stated in the instructions
4. Accept the overwriting of fsgame.lxt
5. Run Stalker-COP.exe as stated in the instructions
6. Set graphics to 1920x1080, medium quality, and either Enhanced DirectX11 or Enhanced DirectX10
7. Close and reopen the game as instructed by the game
8. Click New Game, Difficulty Rookie
9. Let game load
10. Game crashes to desktop

**Expected behavior**
I expect the loading screen to complete with the words Press Any Key to display in the center like how the original Call of Pripyat game displays it and how the OpenXray engine displays it on weak settings. Rgl renderer has weird bugs as well.

**Screenshots, videos**
Full process documented at https://imgur.com/a/uIK67q9

**BugTrap error report**
[OpenXRay_error_report_240216-015936-dx11enhanced.zip](https://github.com/OpenXRay/xray-16/files/14309055/OpenXRay_error_report_240216-015936-dx11enhanced.zip)
[OpenXRay_error_report_240216-020259-dx10enhanced.zip](https://github.com/OpenXRay/xray-16/files/14309056/OpenXRay_error_report_240216-020259-dx10enhanced.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - OpenXRay build version: December 2021 RC1 (Filename: OpenXRay.Gold.64-bit for Windows) 

**Additional context**
The original install of the game works fine before the upgrade to the OpenXray engine. Multiple other Xray Engine games work great including one set to DirectX11 and True Stalker which uses the OpenXray engine. I was hoping to get better performance using the 64bit OpenXray engine. No other games have problems on this PC. 

Rgl renderer had black shadow like artifacts in the distance that stayed near the left and right sides of the screen as I was looking around. The steam jets that show on every other graphics setting didn't show on rgl till I went down the hill. The beeping when standing on the cracked hill where the screen turns red plays at double the rate when the inventory is shown  (by hitting the I key) on the screen for some reason. 

Please give an option to automatically skip the intro videos as well. Thank you for your hard work.

**Comment by Xottab-DUTY** [comment]
This is the crash specific to December 2021 RC1 version.
On DX10/DX11 renderers, you either need to disable SSAO completely, or set it to HDAO with Ultra quality.

The crash was fixed in January 2022, but there was no release published since then, unfortunately.

> Please give an option to automatically skip the intro videos as well.

This is possible even with the original X-Ray engine using the `-nointro` command line key.
You need to create a label to xrEngine.exe file in the `bin` folder and add this key there, and also set `Launch from" parameter to game root folder (where fsgame.ltx lays).
If you are launching the game from Steam, you can add it in the Launch parameters in the game properties.

**Comment by Gold-Vibes** [comment]
Your patience and replying so quickly is appreciated. 

The game runs with SSAO set to `off` but, of course doesn't have SSAO graphics. 
The default settings for SSAO were `High` and `HDAO`. The full process and examples are shown at https://imgur.com/a/iLvL50E . 
I could not find an `Ultra` setting. The game crashes in the typical way as before with SSAO set to `HDAO` and `High`. 

I tried creating a shortcut with the`" -nointro` flag at the end of the `Target` field and modifying the `Start In` field for Enhanced DirectX11 with SSAO set to `off` as shown at the link. The game still has the scaling bug sometimes. 

Thank you for your work on the engine. Do you think a stable version will be released soon?

Extra: 
The audio bug shown in the video at the link differs from Anomaly. I just checked and Anomaly stops the danger sound when the inventory is shown on the screen.

**Comment by Gold-Vibes** [comment]
I tested with the current Nightly build and results are at https://imgur.com/a/mHrSJle

Game seems to run OK on different settings for SSAO. 
There is no `Ultra` setting so I tried `Very High` for SSAO Quality
The game crashed when loading some of the December 2021 saves. 
I was able to save a game with a y in the name with the nightly. 

The scaling bug still occurs will all graphics settings tried: 
`SSAO off` `Graphics Vanilla `
`SSAO HDAO Very High` `Graphics Mode Vanilla`
`SSAO HDAO Very High` `Graphics Mode Enhanced High`
`SSAO HDAO Very High` `Graphics Mode Enhanced Default` (Also had some console errors as shown)
There is no scaling bug in a clean Pripyat install. 
I haven't been able to get the ` -nointro` to work in a clean install when doing the exact same steps when it worked for OpenXray but I will keep trying.
The OpenGL renderer had the display upside down in game and displaying as if it was a double-exposure photo. 

The danger beeping sound doubling in tempo when the inventory screen is visible actually occurs in a clean Pripyat install. Anomaly doesn't do it so I thought it was a bug. 

I greatly appreciate the help but may just stick with the original engine or wait for a release of OpenXray that doesn't have the scaling bug. Thank you very much and I can't wait to see how this turns out!
