### ISSUE TITLE
[ARM64] UI Text Rendering Issues; Skybox Flickering; In-game Intro is Green

### ISSUE THREAD

**Issue by Wooty-B** [OpenXRay/xray-16#878]
**Description of Issue**
I followed installation instructions from the [How to build and setup on Linux](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-How-to-build-and-setup-on-Linux) page, and checked for correct dependencies. After compiling, I build a native package and installed it, copying game files to the specified directory. Upon launching the game, all text is garbled and warped, barely legible, while some lines are completely unreadable.

When launching into the game, the intro is solid green, and remains until gameplay has started. Text in the HUD is warped and spans the screen on occasion. The skybox flickers and twists around while moving, and when standing still it usually corrects itself after a second. Other than these two major distractions, all 3D objects, terrain, game logic and sound seem to be working as intended.

**Steps to reproduce**
1. Compile xray-16 using 'gcc' with parameters: `CFLAGS="-march=native" CXXFLAGS="-march=native" cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_BINDIR=/usr/games`
2. Run `make package`, install with `dpkg -i openxray_*_arm64.deb`
3. Copy game content from a Windows install into: `"~/.local/share/GSC Game World/S.T.A.L.K.E.R. - Call of Pripyat"`
4. Run game from terminal: `xr_3da`
5. Menu text is barely legible, start a New Game, select Rookie, then wait for game to load.
6. Upon starting game, Intro cut-scene is "solid green" until player is loaded.
7. UI text is illegible and spans the screen, skybox flickers constantly. There are no issues with 3D objects, sounds, or gameplay.

**Expected behavior**
All text to be properly rendered throughout the main menus and game HUD. In-game world skybox should be static in appearance to the player. Intro FMV should show video/slide, audio works correctly however.

**Screenshots**
![Main Menu](https://user-images.githubusercontent.com/88899989/130333137-8087c506-adfc-41d7-9df5-7d03f0d5d8cc.jpg)
![Loading Complete Screen](https://user-images.githubusercontent.com/88899989/130333153-ef88ace5-8574-4016-aa52-6ebf5ada7dcc.jpg)
![In-Game HUD Issues](https://user-images.githubusercontent.com/88899989/130333164-b9e03330-3536-4dde-b128-fabc03b38a9f.jpg)
![Flickering Skybox](https://user-images.githubusercontent.com/88899989/130333180-fae2bb49-cdbf-46e0-b56c-4d4ab95f753c.jpg)

**BugTrap error report**
[Terminal Execution Output](https://github.com/OpenXRay/xray-16/files/7026108/xray16_terminal_output.txt)

**Desktop**
 - OS: Ubuntu 21.04 aarch64
 - Built from commit 5bcec2033203ef1b5e5ce3f37da60c0494ce8df9
 - GPU: AMD Radeon Pro WX 4100 w/ Mesa 21.3.0-devel

**Additional context**
Platform is SolidRun HoneyComb LX2K

**Comment by Xottab-DUTY** [comment]
@Wooty-B, please, try to increase the value of the `r2_wait_timeout` console commands to see if it helps? (it may help if my guess is right, but it also can decrease FPS)
Also, you're definitely not on 558th release, I've fixed the description. :)


@vTurbine, maybe you have any additional ideas?

**Comment by OPNA2608** [comment]
> 6. Upon starting game, Intro cut-scene is "solid green" until player is loaded.

See https://github.com/OpenXRay/xray-16/issues/647, https://github.com/OpenXRay/xray-16/pull/701 .

For a quick fix, try extracting this reexported texture into `gamedata/textures/water/`: [water_sbumpvolume.dds.zip](https://github.com/OpenXRay/xray-16/files/7026195/water_sbumpvolume.dds.zip)

**Comment by Wooty-B** [comment]
@Xottab-DUTY I am new to this project, assuming I just launch the game with `./xr_3da -r2_wait_timeout` or `./xr_3da -r2_wait_timeout 10`? Running a combination of those do produce a few amusing menu background artifacts, as well as a couple hiccups when in game. However beyond this I don't see any noticeable changes.
Also whoops... I admit I lazily looked at the project release page and said, "I guess I cloned this version..." o<.o<

@OPNA2608 Thanks, that seemed to do the trick! Intro FMV loads fine now.
Importing and exporting the file into GIMP sounds like the .dds file has metadata that doesn't jive well with the engine. I had a problem importing pictures from my Galaxy phone into a work program because my phone was adding weird metadata to the .jpeg. Maybe doing a diff comparison of before and after will show you what was changed and it may can be fixed with a small script on the fly. (If including this dds in the install doesn't cross any legal barriers that is) Just my two cents.

**Comment by Xottab-DUTY** [comment]
@Wooty-B, you should assume every game has a console and it can be opened using tilde(~) key. This is true for many, many games and it's true for this project.

**Comment by Wooty-B** [comment]
@Xottab-DUTY Apologies, it's not often I've had to do that, thanks for the tip. I ran r2_wait_timeout 100, 500, 766, 1000; doesn't seem to affect anything. Thanks

**Comment by Xottab-DUTY** [comment]
Hm.. I don't know the reason of this issue then, but I hope we will find it.

**Comment by Wooty-B** [comment]
Just an update. I installed RBDOOM-3-BFG and found a similar issue. All pre and in game menu text, in game HUD and dialogue windows are fine, however I noticed all of the in-game computer terminals that display text are stretched and warped, so this affects multiple applications. Maybe there's a correlation between the libraries used, maybe a GL function, but it's either going to be an ARM issue or specifically with my platform.

**Comment by Xottab-DUTY** [comment]
@Wooty-B, can you open an issue in the RBDOOM-3-BFG repo? Maybe it will help to figure out the problem in our repository too)

@a1batross hey there. Maybe, you have an idea why this issue is happening, by chance?

**Comment by a1batross** [comment]
Dunno. Can it be Mesa? Like, if it happens with RBDOOM3, then probably issue may be in OpenGL drivers.

**Comment by xrModder** [comment]
> Hm.. I don't know the reason of this issue then, but I hope we will find it.

Возможно проблема в текстурах. В ЗП шрифты хранятся в формате A8, а не в DXT5 как в ТЧ.

**Comment by xrModder** [comment]
> 7. UI text is illegible and spans the screen

Попробуй заменить шрифты (CoP DXT5 fonts):
https://drive.google.com/file/d/1RH1hJR9Zgi6gIemNuiPyB3WCtXFJwgps/view?usp=sharing

**Comment by Wooty-B** [comment]
> > 7. UI text is illegible and spans the screen
> 
> Попробуй заменить шрифты (CoP DXT5 fonts): https://drive.google.com/file/d/1RH1hJR9Zgi6gIemNuiPyB3WCtXFJwgps/view?usp=sharing

Issue persists after replacing with DXT5 fonts.

At this point I'm willing to bet this is just an issue with my LX2K platform. Most other Linux compatible ARM64 board's aren't going to have the horsepower to drive this game or reliably test at this point in time, so I don't see the reason in keeping focus on this issue.

I recommend closing this issue and waiting to see if other ARM users down the road report similar issues. Thanks again for all of your assistance!

**Comment by xrModder** [comment]
> > > 7. UI text is illegible and spans the screen
> > 
> > Попробуй заменить шрифты (CoP DXT5 fonts): https://drive.google.com/file/d/1RH1hJR9Zgi6gIemNuiPyB3WCtXFJwgps/view?usp=sharing
> 
> Issue persists after replacing with DXT5 fonts.
> 
> At this point I'm willing to bet this is just an issue with my LX2K platform. Most other Linux compatible ARM64 board's aren't going to have the horsepower to drive this game or reliably test at this point in time, so I don't see the reason in keeping focus on this issue.
> 
> I recommend closing this issue and waiting to see if other ARM users down the road report similar issues. Thanks again for all of your assistance!

Нет. Это не проблема твоей платформы, здесь у автора тоже идентичная проблема https://youtu.be/_S9-dL5ayTc, процессор там ARM. Я ошибся что проблема в чтении текстур формата A8. Возможно проблема в чтении координат текстур шрифта (ini файлы).

**Comment by Xottab-DUTY** [comment]
Более вероятная версия – проблема в драйвере ARM64. На это указывает то, что не только шрифты, но и небо поехало.
К тому же, такая проблема происходит в RB Doom 3 BFG, а там вообще другая игра и движок.

**Comment by Xottab-DUTY** [comment]
Recent changes in b0e4de824046f77b9de378ea5d6f3de4e53b22a4 may affect this bug, there's a chance, that it has been fixed.

@Wooty-B, can you test it, please?

**Comment by Wooty-B** [comment]
@Xottab-DUTY I'm currently out of town, but should be able to build and test on 8/15. Acknowledging request.

**Comment by Wooty-B** [comment]
Well, I've tried to build a few times, not sure if it's my setup but still working through a compile error:

`[ 34%] Linking CXX shared library ../../../x64/Release/xrRender_GL.so
CMakeFiles/xrRender_GL.dir/__/xrRender/blenders/glRainBlender.cpp.o:glRainBlender.cpp:vtable for CBlender_rain_msaa: error: undefined reference to 'CBlender_rain_msaa::SetDefine(char const*, char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/Layers/xrRenderPC_GL/CMakeFiles/xrRender_GL.dir/build.make:3123: x64/Release/xrRender_GL.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1185: src/Layers/xrRenderPC_GL/CMakeFiles/xrRender_GL.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 91%] Built target xrGame
make: *** [Makefile:171: all] Error 2
`
Apologies for the delay as well however I will try under an Ubuntu VM soon and see if that make a difference.

**Comment by Xottab-DUTY** [comment]
@Wooty-B, do you have ccache installed? You need to clean its cache.

**Comment by Wooty-B** [comment]
@Xottab-DUTY There may be a problem with one of my dependencies as clearing ccache didn't affect anything. Build and packaged in a VM and was able to get the game up and running.

Unfortunately the same issues still appear, however in-game artifacting is much worse leaving most of the rendered terrain flickering/disappearing. I can record a small clip if needed. Let me know if there's any info/tasks I can provide.

**Comment by Xottab-DUTY** [comment]
@Wooty-B, yes, could you record a clip, please? :)

**Comment by Wooty-B** [comment]
@Xottab-DUTY Here is a highly compressed video, should show issue but if you need a more high quality clip let me know and I will upload to my youtube this evening. :)

~~https://file.io/Up5groYqlygI~~

**Comment by Xottab-DUTY** [comment]
OH MY GOD 😱

**Comment by Wooty-B** [comment]
I don't know if that was from the issues, the quality, or the fact it was deleted prematurely.... :smiley: However, here's a better upload: https://youtu.be/ZNKqzhBQXu0

**Comment by Xottab-DUTY** [comment]
@Wooty-B, can you also try it with console command `r2_wait_timeout 1000`?

**Comment by Wooty-B** [comment]
@Xottab-DUTY No dice. The only difference between both screenshots is I looked up a few pixels then opened up the console again.

https://ibb.co/pwb3zwT
https://ibb.co/3Ms7GKk

I recently got another ARM64 machine that's Snapdragon 7c w/ a modest mobile GPU, so I'm hoping to see if there's any change since there's been past issues with x86 targeted GPU's under ARM. May be a bit before I can test as its a Windows ARM developer platform and not much info on running Linux on them. However I could test Windows on ARM if needed :P

Let me know if there's anything else I can do to assist. I am wondering... If the other persons experiencing this and issues in RBDOOM3 are running integrated GPU's (Mali, Adreno, etc) or AMD GPU's.

**Comment by q4a** [comment]
@Wooty-B Hi. Can you test last commit in `dev` branch? Can you start new game?

**Comment by Wooty-B** [comment]
Hello, apologies for the long delay in response. I have recently rebuilt my system, compiled the game, and getting an error when I launch the game.

[Terminal Log](https://pastebin.com/L2cVtjxq)

I recently bought an nVidia RTX 3060 and tried Doom 3 and the artifacts were gone, since nVidia open drivers don't use Mesa, I'd like to test and see if it really is the culprit.
